name: full_text_search
version: 0.8.0+3
homepage: https://github.com/SunnyApp/full_text_search
description: Full-text search that takes advantages of isolates to prevent locking the main thread
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  collection: ^1.17.2
  equatable: ^2.0.5
  logging: 1.2.0
  meta: ^1.9.1
  sunny_dart: 
    git:
      url: https://github.com/Acuari0/sunny_dart.git
      ref: master
  dartxx: 
    git:
      url: https://github.com/Acuari0/dartxx.git
      ref: master
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
